# Generated by Django 3.2.5 on 2023-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0014_auto_20230519_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'Attente'), ('en_livraison', 'Livraison'), ('annuler', 'Annuler')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('XOF', 'F Cfa'), ('EUR', 'Euro')], default='XOF', max_length=10),
        ),
    ]
