# Generated by Django 3.2.5 on 2023-05-22 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0015_auto_20230519_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'Attente'), ('en_livraison', 'Livraison'), ('annuler', 'Annuler')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('XOF', 'F Cfa'), ('EUR', 'Euro')], default='XOF', max_length=10),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('lat', models.IntegerField(validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('lon', models.IntegerField(validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('status', models.CharField(choices=[('annulee', 'Annulee'), ('en_preparation', 'En Preparation'), ('en_cours', 'En Cours'), ('terminee', 'Terminee')], default='en_preparation', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='boutique.order')),
            ],
        ),
    ]
