# Generated by Django 3.2.5 on 2023-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0017_auto_20230522_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('annulee', 'Annulee'), ('en_preparation', 'En Preparation'), ('en_cours', 'En Cours'), ('terminee', 'Terminee')], default='en_preparation', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'Attente'), ('en_livraison', 'Livraison'), ('annuler', 'Annuler')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('XOF', 'F Cfa'), ('EUR', 'Euro')], default='XOF', max_length=10),
        ),
    ]
